version: '2'
services:
    ttkt-app:
        image: ttkt
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ttkt-mysql:3306/ttkt?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ttkt-mysql:
        extends:
            file: mysql.yml
            service: ttkt-mysql
